CREATE TABLE [dbo].[Candidates] (
    [CandidateID]           INT           IDENTITY (1, 1) NOT NULL,
    [IndentNumber]          VARCHAR (25)  NULL,
    [FirstName]             VARCHAR (100) NULL,
    [LastName]              VARCHAR (100) NULL,
    [Gender]                VARCHAR (1)   NULL,
    [DOB]                   DATETIME      NULL,
    [Email]                 VARCHAR (100) NULL,
    [ContactNumber]         VARCHAR (20)  NULL,
    [Skills]                VARCHAR (200) NULL,
    [CurrentTitle]          VARCHAR (100) NULL,
    [CurrentCompany]        VARCHAR (200) NULL,
    [CurrentLocation]       VARCHAR (100) NULL,
    [Certifications]        VARCHAR (200) NULL,
    [TotalExperience]       DECIMAL (18)  NULL,
    [Passport]              BIT           NULL,
    [Visa]                  BIT           NULL,
    [AadhaarNumber]         VARCHAR (20)  NULL,
    [TravelledOnsiteBefore] BIT           NULL,
    [Reference1]            VARCHAR (100) NULL,
    [Reference1Contact]     VARCHAR (100) NULL,
    [Reference2]            VARCHAR (100) NULL,
    [Reference2Contact]     VARCHAR (100) NULL,
    [ResumeSourceTypeID]    INT           NULL,
    [ResumeSourceDetail]    VARCHAR (300) NULL,
    [CurrentCTC]            MONEY         NULL,
    [ExpectedCTC]           MONEY         NULL,
    [CandidateStatusTypeID] INT           NULL,
    [Remarks]               VARCHAR (500) NULL,
    [CreatedBy]             VARCHAR (200) NULL,
    [CreatedDate]           DATETIME      NULL,
    [ModifiedBy]            VARCHAR (200) NULL,
    [ModifiedDate]          DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([CandidateID] ASC),
    FOREIGN KEY ([IndentNumber]) REFERENCES [dbo].[Indent] ([IndentNumber])
);

