CREATE TABLE [dbo].[Indent] (
    [IndentID]                        INT            IDENTITY (1, 1) NOT NULL,
    [IndentNumber]                    VARCHAR (25)   NOT NULL,
    [IndentDate]                      DATETIME       NULL,
    [BranchID]                        INT            NULL,
    [DepartmentID]                    INT            NULL,
    [Client_Domain]                   VARCHAR (50)   NULL,
    [ProjectStatusID]                 INT            NULL,
    [ReasonID]                        INT            NULL,
    [LocationTypeID]                  INT            NULL,
    [EmploymentTypeID]                INT            NULL,
    [StaffingModeID]                  INT            NULL,
    [ContractMonths]                  INT            NULL,
    [Technologies]                    VARCHAR (250)  NULL,
    [TechnicalSkills]                 VARCHAR (1000) NULL,
    [BehaviouralSkills]               VARCHAR (1000) NULL,
    [PositionTitle]                   VARCHAR (50)   NULL,
    [NoOfPositions]                   INT            NULL,
    [MinExperiance]                   INT            NULL,
    [MaxExperiance]                   INT            NULL,
    [VisaType]                        VARCHAR (20)   NULL,
    [TargetJoinDate]                  DATETIME       NULL,
    [InterviewPanel1]                 VARCHAR (250)  NULL,
    [InterviewPanel2]                 VARCHAR (250)  NULL,
    [InterviewPanel3]                 VARCHAR (250)  NULL,
    [InterviewPanel4]                 VARCHAR (250)  NULL,
    [InterviewPanel5]                 VARCHAR (250)  NULL,
    [ReportingManager]                VARCHAR (100)  NULL,
    [DeploymentLocation]              VARCHAR (200)  NULL,
    [Qualification]                   VARCHAR (200)  NULL,
    [Others]                          VARCHAR (200)  NULL,
    [Indentor]                        VARCHAR (200)  NULL,
    [Indent_Status]                   INT            NULL,
    [IndentorRemarks]                 VARCHAR (500)  NULL,
    [FunctionHead]                    VARCHAR (250)  NULL,
    [FunctionHeadStatusTypeID]        INT            NULL,
    [FunctionHeadStatusDate]          DATETIME       NULL,
    [FunctionHeadRemarks]             VARCHAR (500)  NULL,
    [SeniorVicePresident]             VARCHAR (250)  NULL,
    [SeniorVicePresidentStatusTypeID] INT            NULL,
    [SeniorVicePresidentStatusDate]   DATETIME       NULL,
    [SeniorVicePresidentRemarks]      VARCHAR (500)  NULL,
    [JobDescription]                  VARCHAR (MAX)  NULL,
    [UploadFile_Indents]              VARCHAR (100)  NULL,
    [StatusChangedBy]                 VARCHAR (100)  NULL,
    [AssignedTo]                      VARCHAR (100)  NULL,
    [CreatedBy]                       VARCHAR (100)  NULL,
    [CreatedDate]                     DATETIME       NULL,
    [ModifiedBy]                      VARCHAR (100)  NULL,
    [ModifiedDate]                    DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([IndentID] ASC),
    FOREIGN KEY ([BranchID]) REFERENCES [dbo].[Branches] ([BranchID]),
    FOREIGN KEY ([DepartmentID]) REFERENCES [dbo].[Departments] ([DepartmentID]),
    UNIQUE NONCLUSTERED ([IndentNumber] ASC)
);

