CREATE TABLE [dbo].[InterviewFeedbacks] (
    [InterviewFeedbacksID]             INT           IDENTITY (1, 1) NOT NULL,
    [CandidateID]                      INT           NULL,
    [InterviewRound]                   INT           NULL,
    [InterviewerName]                  VARCHAR (100) NULL,
    [PositionFor]                      VARCHAR (100) NULL,
    [ReleventExperience]               DECIMAL (18)  NULL,
    [ReleventExperienceDiscountReason] VARCHAR (400) NULL,
    [TechKnowledgeAreas]               VARCHAR (100) NULL,
    [TechKnowledgeAreasLevel]          VARCHAR (1)   NULL,
    [TechKnowledgeAreasComments]       VARCHAR (200) NULL,
    [AnalysisAreas]                    VARCHAR (100) NULL,
    [AnalysisAreasLevel]               VARCHAR (1)   NULL,
    [AnalysisAreasComments]            VARCHAR (200) NULL,
    [DesignAreas]                      VARCHAR (100) NULL,
    [DesignAreasLevel]                 VARCHAR (1)   NULL,
    [DesignAreasComments]              VARCHAR (200) NULL,
    [CodingAreas]                      VARCHAR (100) NULL,
    [CodingAreasLevel]                 VARCHAR (1)   NULL,
    [CodingAreasComments]              VARCHAR (200) NULL,
    [DatabaseAreas]                    VARCHAR (100) NULL,
    [DatabaseAreasLevel]               VARCHAR (1)   NULL,
    [DatabaseAreasComments]            VARCHAR (200) NULL,
    [TestingAreas]                     VARCHAR (100) NULL,
    [TestingAreasLevel]                VARCHAR (1)   NULL,
    [TestingAreasComments]             VARCHAR (200) NULL,
    [ResultOrientationLevel]           VARCHAR (1)   NULL,
    [ResultOrientationComments]        VARCHAR (200) NULL,
    [CommunicationSkillsLevel]         VARCHAR (1)   NULL,
    [CommunicationSkillsComments]      VARCHAR (200) NULL,
    [TeamWorkingLevel]                 VARCHAR (1)   NULL,
    [TeamWorkingComments]              VARCHAR (200) NULL,
    [LeadershipCapabilityLevel]        VARCHAR (1)   NULL,
    [LeadershipCapabilityComments]     VARCHAR (200) NULL,
    [AttitudeLevel]                    VARCHAR (1)   NULL,
    [AttitudeComments]                 VARCHAR (200) NULL,
    [OverallRatingLevel]               VARCHAR (1)   NULL,
    [OverallRatingComments]            VARCHAR (200) NULL,
    [SelectionReason]                  VARCHAR (200) NULL,
    [PositivesRemarks]                 VARCHAR (200) NULL,
    [ConcernsGaps]                     VARCHAR (200) NULL,
    [PositionRecomended]               VARCHAR (200) NULL,
    [PositionSuggested]                VARCHAR (200) NULL,
    [AlternaticeCompetancy]            VARCHAR (200) NULL,
    [TrainingsNeededTechnical]         VARCHAR (200) NULL,
    [TrainingNeededBehavioral]         VARCHAR (200) NULL,
    [Status]                           INT           NULL,
    [CreatedBy]                        VARCHAR (200) NULL,
    [CreatedDate]                      DATETIME      NULL,
    [ModifiedBy]                       VARCHAR (200) NULL,
    [ModifiedDate]                     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([InterviewFeedbacksID] ASC),
    FOREIGN KEY ([CandidateID]) REFERENCES [dbo].[Candidates] ([CandidateID])
);

